### ISSUE TITLE
Switch cases

### ISSUE THREAD

**Issue by Vali18** [KurtE/Open_CM904#2]
Hi @KurtE ,

This looks awesome. I just uploaded your code on the cm904 board, how do i switch cases? 
I tried to type the case number or letter on the serial monitor and press enter, but nothing happens...am i doing something wrong?

**Comment by KurtE** [comment]
There are a few different programs up here also which branch of the code? 

What is the line ending set to at the bottom of the terminal monitor?  Try setting to both NL and CR

**Comment by Vali18** [comment]
hI @KurtE What do u mean? Sorry not clear. I just uploaded your test code AX12_Test_OpenCM.ino on my openCM904 + ExpansionBoard 485 and when I open the serial terminal I see this:

CM9.04 Servo Test program
Default PortHandler Servos on Serial3 (on 485 expansion Board)
System Voltage in 10ths: 255
0 - All Servos off
1 - All Servos center
2 - Set Servo position [<Servo>] <Position> [<Speed>]
3 - Set Servo Angle
4 - Get Servo Positions
5 - Find All Servos
6 - Set Servo return delay time
8 - Set ID: <old> <new>
9 - Print Servo Values
t - Toggle track Servos
h - hold [<sn>]
f - free [<sn>]
s - switch Serial Bus
:

and if i simply try to type any of these number (like 4 to Get Servo Positions) on the serial and press enter nothing happens.

**Comment by KurtE** [comment]
Looks like this is from the default branch of this library.  You might want to switch to the WIP_Suppot_XL320_Servos branch... 

I am assuming you are using the Arduino IDE Serial monitor?
Did you change the Line ending from NONE to something else like you can see in the image:
![serial_monitor](https://user-images.githubusercontent.com/1558080/44124728-833ec380-9fe3-11e8-97d0-afc7ca2b52b2.jpg)
This is showing the scan that looks for all servos

I then use the 4 command and it shows the position of the one servo found...
```
Cmd: 4
21:376 244 0
PrintServo Voltage called
```
The main/default branch was before I started working with Protocol 2 stuff and was mainly only for AX servos.  I should soon move this other branch to be the main one. 

Note: the command line code looks for characters in the range of 10-15 (things like CR, NL, LF, to terminate a command, so if the Line ending is none it does not process the input line
